### ISSUE TITLE
[Bug]: Crash to desktop in score sync

### ISSUE THREAD

**Issue by x416C6578** [Turing-Complete-Game/Suggestions-and-Issues#144] opened 2021-11-30 18:19 UTC
### What happened?

Load the game, click "score sync", wait ~10 seconds and crash to desktop

### Version

Latest (Beta 0.342)

### Operating System

W10 21H1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2021-11-30 18:22
Duplicate of #120

**Closed by MegaIng** 2021-11-30 18:22 UTC
Labels: bug, triage
