### ISSUE TITLE
[Bug]: Components scores in sandbox are still default

### ISSUE THREAD

**Issue by Gelthir** [Turing-Complete-Game/Suggestions-and-Issues#223] opened 2024-09-11 10:52 UTC
### Discord Thread

https://discord.com/channels/828292123936948244/1283373116999073855

### What happened?

Xor/xnor gate score is off
They are both scored 4/6, even when the design for their level is 3/4

A whole lot of components have wonky [Default] scores though I see now
like 8-bit add is 100/100, 8-bit mux is 50/8

### Version

0.1147 Beta

### What OSes are you seeing the problem on?

Windows

**Comment by Stuffe** [comment] 2024-09-12 05:43
I believe this was the assembler issue and it is now fixed?

**Comment by Stuffe** [comment] 2024-09-12 05:56
I think I just fixed this before being able to test. Otherwise I can't reproduce.
(Also, make sure you run the XOR level so the score shows up on the level map)

**Closed as completed by Stuffe** 2024-09-12 05:56 UTC
Labels: bug
