### ISSUE TITLE
[Bug]: The game crashes on boot

### ISSUE THREAD

**Issue by TownesKing** [Turing-Complete-Game/Suggestions-and-Issues#335] opened 2022-02-26 16:28 UTC
### What happened?

I am on a M1 apple laptop and when I boot the game it immediately crashes before the application fully opens to the point where you can see anything

Here is a link to the crash report that Apple gave after the crash.
[Untitled document.txt](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/8147003/Untitled.document.txt)

### Version

Latest

### Operating System

macOS Monterey

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-02-26 16:29
Duplicate of #266

**Closed by MegaIng** 2022-02-26 16:29 UTC
Labels: bug, triage
