### ISSUE TITLE
[Bug]: incorrect wire color change 

### ISSUE THREAD

**Issue by fifthFunction** [Turing-Complete-Game/Suggestions-and-Issues#157] opened 2021-12-03 05:50 UTC
### What happened?

when changing a wires color in "delay score mode" the ends of the wire dont update
when leaving the mode everything is update correctly tho
![image](https://user-images.githubusercontent.com/61679450/144552295-1d516a81-086b-4438-ab27-d145c860c04b.png)

### Version

Latest

### Operating System

win10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2021-12-03 11:10
Duplicate of #24

**Closed by MegaIng** 2021-12-03 11:10 UTC
Labels: bug, triage
