### ISSUE TITLE
[Bug]: Broken level Storage Cracker

### ISSUE THREAD

**Issue by snatani** [Turing-Complete-Game/Suggestions-and-Issues#58] opened 2021-11-16 08:50 UTC
### What happened?

The level Storage Locker seems to be broken. Sending in the same number to the output seems to do the trick. Basically a code like send 20 to reg0; send reg0 to out; send inp to reg3; send reg0 to out; will let me advance the level.
![image](https://user-images.githubusercontent.com/12123831/141952967-b3aad3c9-d804-4cdd-ada9-a289c2af8866.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2021-11-16 13:31
Probably related, if not duplicate of #28

**Comment by bombitmanbomb** [comment] 2021-11-16 15:35
Duplicate of #28 
Same Outcome achieved programmatically: If `Input` is 1, and is sent to `Output`, solution of 1 will solve level every time.

**Closed by bombitmanbomb** 2021-11-16 15:35 UTC
Labels: bug, triage
