### ISSUE TITLE
[Bug]: Edit Watched State causes crash

### ISSUE THREAD

**Issue by Apitheia** [Turing-Complete-Game/Suggestions-and-Issues#300] opened 2022-02-09 16:38 UTC
### What happened?

Clicking Edit Watched State on my completed Overture crashes the game without error. The only way to not crash is to delete all custom components first. Deleting all custom components, clicking Edit Watch States, and then ctrl-z to bring back the last custom component deleted crashes with memory could not be read. Creating a new schematic does not cause a crash, even with 6 custom registers and a counter already placed.

This is a new playthrough after the latest update.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-02-21 12:37
Duplicate of #298

**Closed by MegaIng** 2022-02-21 12:37 UTC
Labels: bug, reproduction needed, triage
