### ISSUE TITLE
[Bug]: The game does not start at all. MacOS Monterey, M1 Max 2021.

### ISSUE THREAD

**Issue by matnick** [Turing-Complete-Game/Suggestions-and-Issues#334] opened 2022-02-25 20:10 UTC
### What happened?

The game doesn't start at all. 

Here is the Apple generated error report:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Turing Complete [5296]
Path:                  /Users/USER/Library/Application Support/Steam/*/Turing Complete.app/Contents/MacOS/Turing Complete
Identifier:            TuringComplete
Version:               1.0 (1.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-02-25 23:04:21.0545 +0300
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        5062D7A0-BF95-CC53-9178-8F3389E56072


Time Awake Since Boot: 35000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  MainThrd  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes:       0x0000000000000001, 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [5296]

VM Region Info: 0x10 is not in any region.  Bytes before following region: 4306436080
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100af0000-102bd0000    [ 32.9M] r-x/r-x SM=COW  ...ring Complete

Application Specific Information:
dyld4 config: DYLD_LIBRARY_PATH= DYLD_INSERT_LIBRARIES=/Users/matrix/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamloader.dylib:/Users/matrix/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/gameoverlayrenderer.dylib


Thread 0 Crashed:: MainThrd Dispatch queue: com.apple.main-thread
0   Turing Complete               	       0x1021c6da0 Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) + 176
1   Turing Complete               	       0x100cd3fac GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) + 29620
2   Turing Complete               	       0x100ca40a0 GDScript::_create_instance(Variant const**, int, Object*, bool, Variant::CallError&) + 436

Thread 1:
0   libsystem_pthread.dylib       	       0x1c6824010 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1c6824010 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1c6824010 start_wqthread + 0

Thread 4:
0   libsystem_kernel.dylib        	       0x1c67f10c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1c6829808 _pthread_cond_wait + 1228
2   libc++.1.dylib                	       0x1c6777ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Turing Complete               	       0x10231d504 _IP_ResolverPrivate::_thread_function(void*) + 132
4   libsystem_pthread.dylib       	       0x1c6824024 thread_start + 8

Thread 5:
0   libsystem_kernel.dylib        	       0x1c67f10c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1c6829808 _pthread_cond_wait + 1228
2   libc++.1.dylib                	       0x1c6777ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3   Turing Complete               	       0x101f2c9a0 VisualServerScene::_gi_probe_bake_thread() + 152
4   libsystem_pthread.dylib       	       0x1c6824024 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	       0x1c6824010 start_wqthread + 0

Thread 7:: AMCP Logging Spool
0   libsystem_kernel.dylib        	       0x1c67ed990 semaphore_wait_trap + 8
1   caulk                         	       0x1cf1fc8ac caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1cf1df65c caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1cf1df27c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x1c6829240 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1c6824024 thread_start + 8

Thread 8:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	       0x1c67ed954 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1c67edd00 mach_msg + 76
2   CoreAudio                     	       0x1c852fef0 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 104
3   CoreAudio                     	       0x1c83bee04 HALC_ProxyIOContext::IOWorkLoop() + 3360
4   CoreAudio                     	       0x1c83bdae0 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 100
5   CoreAudio                     	       0x1c8589420 HALB_IOThread::Entry(void*) + 88
6   libsystem_pthread.dylib       	       0x1c6829240 _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1c6824024 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000014814eaa8   x1: 0x0000600003ab0798   x2: 0x000000016f30e818   x3: 0x0000000000000001
    x4: 0x000000016f30e7d0   x5: 0x000000016f30e938   x6: 0x0000000000000000   x7: 0x00000001c67e77dc
    x8: 0x00006000015de550   x9: 0x0000000000000010  x10: 0x0000000000000018  x11: 0x0000000000000000
   x12: 0x000000014814eaa8  x13: 0x0000000000000000  x14: 0x00000000707ace52  x15: 0x000000000000005d
   x16: 0x000000000000005d  x17: 0x0000000000100000  x18: 0x00000001091373fc  x19: 0x000000016f30e7d0
   x20: 0x000000016f30e938  x21: 0x0000000000000001  x22: 0x000000014814eaa8  x23: 0x0000600003ab0798
   x24: 0x0000000102903b36  x25: 0x0000000000000001  x26: 0x0000000000000095  x27: 0x000000016f30e7d0
   x28: 0x0000000102860882   fp: 0x000000016f30eaf0   lr: 0x0000000100cd3fac
    sp: 0x000000016f30e730   pc: 0x00000001021c6da0 cpsr: 0x80001000
   far: 0x0000000000000010  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x100af0000 -        0x102bcffff TuringComplete (1.0) <3c927619-3594-3039-a89e-72d08cdc110f> /Users/USER/Library/Application Support/Steam/*/Turing Complete.app/Contents/MacOS/Turing Complete
       0x1c6822000 -        0x1c682efff libsystem_pthread.dylib (*) <f7b2eccf-e6f1-3109-ae81-9028c0b8332a> /usr/lib/system/libsystem_pthread.dylib
       0x1c67ec000 -        0x1c6821fff libsystem_kernel.dylib (*) <384945e6-dd71-37e5-9a3d-84fff14a1e60> /usr/lib/system/libsystem_kernel.dylib
       0x1c676e000 -        0x1c67d1fff libc++.1.dylib (*) <0eb3a986-b1bc-3f18-b7cc-51e2e5e00dc3> /usr/lib/libc++.1.dylib
       0x1cf1dd000 -        0x1cf204fff com.apple.audio.caulk (1.0) <f8f1663b-806a-3544-9a8b-2a595d06dfdd> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x1c81f6000 -        0x1c8924fff com.apple.audio.CoreAudio (5.0) <b1a13ce9-3aa2-3411-b64c-f9d2d4b293a0> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=881.2M resident=0K(0%) swapped_out_or_unallocated=881.2M(100%)
Writable regions: Total=1.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.0G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG backing stores                 2880K        4 
ColorSync                          544K       24 
CoreAnimation                       16K        1 
CoreGraphics                        16K        1 
CoreUI image data                  160K        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           273.4M       44 
MALLOC guard page                  192K        9 
MALLOC_MEDIUM (reserved)         352.0M        3         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3 
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                        1.0G       35 
VM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)
__AUTH                            1906K      187 
__AUTH_CONST                      11.4M      348 
__DATA                            8771K      339 
__DATA_CONST                      12.0M      354 
__DATA_DIRTY                       745K      120 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       584.0M       11 
__OBJC_CONST                      1598K      153 
__OBJC_RO                         82.1M        1 
__OBJC_RW                         3104K        1 
__TEXT                           297.1M      372 
__UNICODE                          588K        1 
dyld private memory               1024K        1 
mapped file                       74.4M       19 
shared memory                     18.6M       19 
===========                     =======  ======= 
TOTAL                              3.1G     2077 
TOTAL, minus reserved VM space     2.4G     2077 



-----------
Full Report
-----------

{"app_name":"Turing Complete","timestamp":"2022-02-25 23:04:21.00 +0300","app_version":"1.0","slice_uuid":"3c927619-3594-3039-a89e-72d08cdc110f","build_version":"1.0","platform":1,"bundleID":"TuringComplete","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.2.1 (21D62)","incident_id":"9DB24F28-B8FA-42B6-B7D0-0A8E4AE258E6","name":"Turing Complete"}
{
  "uptime" : 35000,
  "procLaunch" : "2022-02-25 23:04:19.7224 +0300",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "procStartAbsTime" : 852135483677,
  "coalitionID" : 4597,
  "osVersion" : {
    "train" : "macOS 12.2.1",
    "build" : "21D62",
    "releaseType" : "User"
  },
  "captureTime" : "2022-02-25 23:04:21.0545 +0300",
  "incident" : "9DB24F28-B8FA-42B6-B7D0-0A8E4AE258E6",
  "bug_type" : "309",
  "pid" : 5296,
  "procExitAbsTime" : 852167156165,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Turing Complete",
  "procPath" : "\/Users\/USER\/Library\/Application Support\/Steam\/*\/Turing Complete.app\/Contents\/MacOS\/Turing Complete",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0","CFBundleVersion":"1.0","CFBundleIdentifier":"TuringComplete"},
  "storeInfo" : {"deviceIdentifierForVendor":"0F271DD8-BE1A-58A9-A02D-57D63D46A395","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "TuringComplete",
  "crashReporterKey" : "5062D7A0-BF95-CC53-9178-8F3389E56072",
  "sip" : "enabled",
  "vmRegionInfo" : "0x10 is not in any region.  Bytes before following region: 4306436080\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      100af0000-102bd0000    [ 32.9M] r-x\/r-x SM=COW  ...ring Complete",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000010","rawCodes":[1,16],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000010"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":5296},
  "vmregioninfo" : "0x10 is not in any region.  Bytes before following region: 4306436080\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      100af0000-102bd0000    [ 32.9M] r-x\/r-x SM=COW  ...ring Complete",
  "asi" : {"dyld":["dyld4 config: DYLD_LIBRARY_PATH= DYLD_INSERT_LIBRARIES=\/Users\/matrix\/Library\/Application Support\/Steam\/Steam.AppBundle\/Steam\/Contents\/MacOS\/steamloader.dylib:\/Users\/matrix\/Library\/Application Support\/Steam\/Steam.AppBundle\/Steam\/Contents\/MacOS\/gameoverlayrenderer.dylib"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":250432,"threadState":{"x":[{"value":5504297640},{"value":105553177806744},{"value":6160443416},{"value":1},{"value":6160443344},{"value":6160443704},{"value":0},{"value":7625144284,"symbolLocation":0,"symbol":"__cxxabiv1::__class_type_info::search_above_dst(__cxxabiv1::__dynamic_cast_info*, void const*, void const*, int, bool) const"},{"value":105553139197264},{"value":16},{"value":24},{"value":0},{"value":5504297640},{"value":0},{"value":1887096402},{"value":93},{"value":93},{"value":1048576},{"value":4447237116},{"value":6160443344},{"value":6160443704},{"value":1},{"value":5504297640},{"value":105553177806744},{"value":4337974070,"symbolLocation":436866,"symbol":"png_formatted_warning.valid_parameters"},{"value":1},{"value":149},{"value":6160443344},{"value":4337305730}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4308418476},"cpsr":{"value":2147487744},"fp":{"value":6160444144},"sp":{"value":6160443184},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4330384800,"matchesCrashFrame":1},"far":{"value":16}},"name":"MainThrd","queue":"com.apple.main-thread","frames":[{"imageOffset":23948704,"symbol":"Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&)","symbolLocation":176,"imageIndex":0},{"imageOffset":1982380,"symbol":"GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*)","symbolLocation":29620,"imageIndex":0},{"imageOffset":1786016,"symbol":"GDScript::_create_instance(Variant const**, int, Object*, bool, Variant::CallError&)","symbolLocation":436,"imageIndex":0}]},{"id":250433,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":250434,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":250439,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":250443,"frames":[{"imageOffset":20672,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30728,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":1},{"imageOffset":40412,"symbol":"std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":28,"imageIndex":3},{"imageOffset":25351428,"symbol":"_IP_ResolverPrivate::_thread_function(void*)","symbolLocation":132,"imageIndex":0},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":250444,"frames":[{"imageOffset":20672,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":2},{"imageOffset":30728,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":1},{"imageOffset":40412,"symbol":"std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":28,"imageIndex":3},{"imageOffset":21219744,"symbol":"VisualServerScene::_gi_probe_bake_thread()","symbolLocation":152,"imageIndex":0},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":250445,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":250446,"name":"AMCP Logging Spool","frames":[{"imageOffset":6544,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":2},{"imageOffset":129196,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":4},{"imageOffset":9820,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":4},{"imageOffset":8828,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":4},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":250472,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":2},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":2},{"imageOffset":3383024,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":104,"imageIndex":5},{"imageOffset":1871364,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":3360,"imageIndex":5},{"imageOffset":1866464,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":100,"imageIndex":5},{"imageOffset":3748896,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":88,"imageIndex":5},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4306436096,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "TuringComplete",
    "size" : 34471936,
    "uuid" : "3c927619-3594-3039-a89e-72d08cdc110f",
    "path" : "\/Users\/USER\/Library\/Application Support\/Steam\/*\/Turing Complete.app\/Contents\/MacOS\/Turing Complete",
    "name" : "Turing Complete",
    "CFBundleVersion" : "1.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7625383936,
    "size" : 53248,
    "uuid" : "f7b2eccf-e6f1-3109-ae81-9028c0b8332a",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7625162752,
    "size" : 221184,
    "uuid" : "384945e6-dd71-37e5-9a3d-84fff14a1e60",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7624646656,
    "size" : 409600,
    "uuid" : "0eb3a986-b1bc-3f18-b7cc-51e2e5e00dc3",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7769804800,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 163840,
    "uuid" : "f8f1663b-806a-3544-9a8b-2a595d06dfdd",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7652466688,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 7532544,
    "uuid" : "b1a13ce9-3aa2-3411-b64c-f9d2d4b293a0",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 7622213632,
  "size" : 3091218432,
  "uuid" : "296eb28e-6aeb-3129-8fa6-feb92261a4eb"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=881.2M resident=0K(0%) swapped_out_or_unallocated=881.2M(100%)\nWritable regions: Total=1.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.0G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG backing stores                 2880K        4 \nColorSync                          544K       24 \nCoreAnimation                       16K        1 \nCoreGraphics                        16K        1 \nCoreUI image data                  160K        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           273.4M       44 \nMALLOC guard page                  192K        9 \nMALLOC_MEDIUM (reserved)         352.0M        3         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.1M        9 \nStack                             12.2M        9 \nVM_ALLOCATE                        1.0G       35 \nVM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)\n__AUTH                            1906K      187 \n__AUTH_CONST                      11.4M      348 \n__DATA                            8771K      339 \n__DATA_CONST                      12.0M      354 \n__DATA_DIRTY                       745K      120 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       584.0M       11 \n__OBJC_CONST                      1598K      153 \n__OBJC_RO                         82.1M        1 \n__OBJC_RW                         3104K        1 \n__TEXT                           297.1M      372 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                       74.4M       19 \nshared memory                     18.6M       19 \n===========                     =======  ======= \nTOTAL                              3.1G     2077 \nTOTAL, minus reserved VM space     2.4G     2077 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "MainThrd",
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "620161cb295c182621eced20"
      },
      "deploymentId" : 240000389
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000111
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000249
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,2, BootROM 7429.81.3, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: LG Ultra HD, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOn, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Dec 13 2021 17:12:34 version 20.10.853.31.8.7.109 FWID 01-804e92d8
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: Razer DeathAdder V2
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
```

<img width="369" alt="Screenshot 2022-02-25 at 23 08 50" src="https://user-images.githubusercontent.com/5347302/155791474-568c654c-6533-4600-8161-a963348cd65d.png">

### Version

Latest

### Operating System

MacOS Monterey

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-02-25 20:36
Duplicate of #266

**Closed by MegaIng** 2022-02-25 20:36 UTC
Labels: bug, triage
