### ISSUE TITLE
[Bug]: Empty custom component

### ISSUE THREAD

**Issue by kedesiklem** [Turing-Complete-Game/Suggestions-and-Issues#212] opened 2021-12-28 17:59 UTC
### What happened?

When removing a custom component and renaming an other one with the name of the removed one, an empty custom component replace the renamed one. (I've done it because I've edit the "COND" component just after completing the level, and instead of overwriting it, the game has create "COND2")

### Version

Latest

### Operating System

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SunCatMC** [comment] 2021-12-30 20:31
If by "empty component" you mean one in component menu on the right, that gets a completely white icon - then yeah, I can reproduce that.
![image](https://user-images.githubusercontent.com/26610984/147785685-83ee9d60-1f9b-44f5-a000-0abd3e1099e0.png)

You just need to rename a custom component, that was created via a level, to any other name (said name doesn't have to be one that existed before). These "empty components" can be placed tho, and look just like the component that was created via the level, and exist in the menu on the right until you exit the game.

If what you experienced doesn't match with the bug that I am describing, please tell more about the bug that you saw (screenshots would be appreciated!)

**Comment by SunCatMC** [comment] 2022-02-21 12:32
seems to be fixed as of 0.544

**Closed by SunCatMC** 2022-02-21 12:32 UTC
Labels: bug, Severity: Low, Category: Custom Components
