### ISSUE TITLE
no input [Bug]: 

### ISSUE THREAD

**Issue by Liuphillip** [Turing-Complete-Game/Suggestions-and-Issues#357] opened 2022-03-17 02:52 UTC
### What happened?

in the level "odd number of signals" there is no input

### Version

Latest

### Operating System

windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-17 09:13
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

Duplicate of #351

**Closed by MegaIng** 2022-03-17 09:13 UTC
Labels: bug, triage
