### ISSUE TITLE
[Bug]: BYTE NOT, BYTE OR level has no inputs. Switch has no output. Crashes to desktop when attempting to "run" or "next tick"

### ISSUE THREAD

**Issue by winry-fruitiwi** [Turing-Complete-Game/Suggestions-and-Issues#359] opened 2022-03-17 09:12 UTC
### What happened?

After a recent update, inputs and outputs for the levels I'm currently working on have mysteriously disappeared ; ; I can place gates and wires, but when I try to run anything, the game crashes to desktop.

![2022 Mar 17 2 04 37 AM](https://user-images.githubusercontent.com/86872872/158775299-4106f7d4-43e8-4d70-8196-e9a7726498cc.png)
![2022 Mar 17 2 05 38 AM](https://user-images.githubusercontent.com/86872872/158775301-e47ef0ad-f0b9-442e-a106-61e25e2d3337.png)
![2022 Mar 17 2 05 32 AM](https://user-images.githubusercontent.com/86872872/158775304-e2b45946-68ae-4d08-bf4f-0a76921acf13.png)

Here is my latest log and save file (I think!)
[godot.log](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/8283244/godot.log)
[progress.zip](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/8283246/progress.zip)

### Version

Latest

### Operating System

Win11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-17 09:14
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

Duplicate of #351

(also, it's preferable to not upload your save folder because it sadly contains a private token atm)

**Closed by MegaIng** 2022-03-17 09:14 UTC
Labels: bug, triage

**Comment by winry-fruitiwi** [comment] 2022-03-17 09:51
Thank you! Sorry for not searching more thoroughly through the closed issues first!
