### ISSUE TITLE
[Bug]: Condition level doesn't give input.

### ISSUE THREAD

**Issue by aristakesyanl** [Turing-Complete-Game/Suggestions-and-Issues#355] opened 2022-03-14 12:09 UTC
### What happened?

Condition level doesn't give any inputs.
![Screenshot_3](https://user-images.githubusercontent.com/60519263/158169223-0669a432-c209-4910-b60c-d1ca25d2fbc6.png)

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-14 12:11
Duplicate of #351

Create a new schematic via the menu in the top left.

**Closed by MegaIng** 2022-03-14 12:11 UTC
Labels: bug, triage
