### ISSUE TITLE
[Bug]: Missing inputs

### ISSUE THREAD

**Issue by ElTruenito** [Turing-Complete-Game/Suggestions-and-Issues#373] opened 2022-03-25 20:12 UTC
### What happened?

The level "Unsigned Less" is missing the inputs. I can't solve i
![Inked20220325210923_1_LI](https://user-images.githubusercontent.com/102387423/160194336-b9d3837c-d996-4caf-ba6c-3e17bff3c0bf.jpg)
t

### Version

Latest

### Operating System

Windows 10 Pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-25 20:13
Duplicate of #351 . As also mentioned in the main menu, create a new schematic via the menu in the top left.

**Closed by MegaIng** 2022-03-25 20:13 UTC
Labels: bug, triage
