### ISSUE TITLE
[Bug]: Odd Ticks impossible to complete

### ISSUE THREAD

**Issue by Michellejanehandy** [Turing-Complete-Game/Suggestions-and-Issues#461] opened 2022-06-02 14:33 UTC
### What happened?

When starting the level Odd Ticks, Delay components do not appear on top right, instead basic logic components only appear. This renders the level impossible to complete since the level is focused on Delay components

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-06-02 15:56
Fixed in 0.820 (and duplicate of #460)

**Closed by MegaIng** 2022-06-02 15:56 UTC
Labels: bug, triage
