### ISSUE TITLE
[Bug]: Level "Byte Constant" does not have an output node

### ISSUE THREAD

**Issue by Potato2357** [Turing-Complete-Game/Suggestions-and-Issues#362] opened 2022-03-18 01:37 UTC
### What happened?

 The level "Byte Constant" does not have an output node, resulting in the game crashing when running the next ticks.

### Version

Latest

### Operating System

macOS Monterey

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-18 08:25
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

Duplicate of #351

**Closed by MegaIng** 2022-03-18 08:25 UTC
Labels: bug, triage
