### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Zerrocool518** [Turing-Complete-Game/Suggestions-and-Issues#471] opened 2022-06-16 12:08 UTC
### What happened?

I cant start the game anymore, neither with proton, nor without or sth i tried all versions, nothing will work. I also tried to change to the dev version but its always the same: Window opens, then promptly crashes

### Version

Latest

### Operating System

Clear Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-06-16 12:08
Duplicate of #469

**Closed** 2022-07-08 12:20 UTC
Labels: bug, triage
