### ISSUE TITLE
[Bug]: Level "Saving Gracefully" no Input

### ISSUE THREAD

**Issue by DuStinkst** [Turing-Complete-Game/Suggestions-and-Issues#360] opened 2022-03-17 17:44 UTC
### What happened?

As stated in the titel, the level "saving gracefully" does not have any inputs for me. I don't know if it's a bug or a change and you have to do the inputs for yourself, but before I waste 2h to do the inputs with ONs, I'm asking here.
Thanks in advance,
-- Me

![Screenshot (99)](https://user-images.githubusercontent.com/57415368/158862847-5f2c326e-008e-4f55-a2bf-3bc33595aa86.png)

### Version

Latest

### Operating System

Windows 10 Version 21H1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-17 17:44
Create a new schematic via the menu in the top left, make sure to switch to it. Then the IO should be there.

Duplicate of #351

**Closed by MegaIng** 2022-03-17 17:44 UTC
Labels: bug, triage

**Comment by DuStinkst** [comment] 2022-03-17 17:46
That was fast, 
thanks it worked!
