### ISSUE TITLE
[Bug]: Possible memory leak in score tables

### ISSUE THREAD

**Issue by richard-whitty** [Turing-Complete-Game/Suggestions-and-Issues#145] opened 2021-11-30 21:28 UTC
### What happened?

in 0.342 beta if you click the score sync menu item it seems to hang and leak memory.
Takes a few seconds to get to 30gb then my computer OOMs.

Because of the nature of this issue I can't really provide a backtrace or memory dump. If it would be helpful I could try running it in it's own namespace and limiting that. I have overcommit enabled so it would seem the game is actually hitting the memory being allocated.

You probably know of the bug already but if I'm the only one then let me know if there's any diagnostics that'd be helpful.

### Version

Latest

### Operating System

linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2021-11-30 21:32
Duplicate of #120

**Closed by MegaIng** 2021-11-30 21:32 UTC
Labels: bug, triage
