### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by asudala** [Turing-Complete-Game/Suggestions-and-Issues#470] opened 2022-06-16 11:30 UTC
### What happened?

I completed the quest for "The bus" and crashed when I proceeded to the next stage. What is the cause?

### Version

Latest

### Operating System

windows 10 (21H2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-06-16 11:34
Duplicate of #469 

Cause is currently unknown.

**Closed by MegaIng** 2022-06-16 11:34 UTC
Labels: bug, triage
