### ISSUE TITLE
[Bug]: "Registers" Level - Diagram missing connection to "Code" byte

### ISSUE THREAD

**Issue by mtadd** [Turing-Complete-Game/Suggestions-and-Issues#349] opened 2022-03-13 17:12 UTC
### What happened?

Tests include 2 bytes "Code" and "Input", but there's nowhere in wiring diagram to connect to "Code" byte.  There are only the "Input" and "Output" bytes endpoints.  I tried creating a new schematic diagram, but that too didn't have an endpoint to connect to the "Code" byte.

### Version

Latest

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-13 21:24
Are you coming back to this level and already have the Program component available? If that is the case, use a Program + Counter instead of the extra input.

**Comment by mtadd** [comment] 2022-03-14 01:13
No, I'm starting from the beginning working my way up the level diagram.
I'll pass it for now.

**Comment by Pixpeg** [comment] 2022-03-14 16:48
Same issue for me. Bought and started game fresh two days ago and can't go any further due to missing Code node in "Registers" level. 
0.585 Beta

**Comment by razurac** [comment] 2022-03-14 19:10
Exactly same problem here too.

**Comment by MegaIng** [comment] 2022-03-14 19:47
I just recompleted all levels up to this point to test this, I can't reproduce; for me both inputs appear. Can you guys try creating a new schematic on the newest version (0.585) again? Otherwise upload your save folder to https://turingcomplete.game/report_bug and reference this issue + your name (email).

**Comment by razurac** [comment] 2022-03-14 20:27
> I just recompleted all levels up to this point to test this, I can't reproduce; for me both inputs appear. Can you guys try creating a new schematic on the newest version (0.585) again? Otherwise upload your save folder to https://turingcomplete.game/report_bug and reference this issue + your name (email).


This seem to have fixed it. Thanks:)

**Comment by mtadd** [comment] 2022-03-14 20:57
Fixed - I created a new schematic, and I now see the "Instruction" in the
inputs, and I see it also now in the upper-left corner of the wiring
diagram.

**Comment by Pixpeg** [comment] 2022-03-14 21:08
Yes - creating a new schematic worked. The missing input is now there.
Thanks!

**Comment by MegaIng** [comment] 2022-03-14 21:19
Ok, then this is a duplicate of #351 (with an added complication somewhere that made the create new schematic solution not work for some versions)

**Closed by MegaIng** 2022-03-14 21:19 UTC
Labels: bug, triage
