### ISSUE TITLE
[Request]: Rotate selection

### ISSUE THREAD

**Issue by eReN17** [Turing-Complete-Game/Suggestions-and-Issues#44] opened 2021-11-14 21:57 UTC
Rotate all selected components at once would be a nice addition 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment] 2021-11-15 18:14
This is currently in the development version, not sure if it's in the main branch yet though.

**Comment by bombitmanbomb** [comment] 2021-11-16 21:09
Duplicate of #30 
Available in Development Build.

**Closed by bombitmanbomb** 2021-11-16 21:09 UTC
Labels: duplicate, enhancement
