### ISSUE TITLE
[Bug]: custom components not updating changes

### ISSUE THREAD

**Issue by fifthFunction** [Turing-Complete-Game/Suggestions-and-Issues#66] opened 2021-11-17 18:40 UTC
### What happened?

leaving a circular dependency within a custom component then removing it as your last action before leaving again will not save any of the last changes
![8AC9BknyaE](https://user-images.githubusercontent.com/61679450/142261847-043d857c-444e-4743-b3bf-3bc3f982ed7c.gif)

### Version

Latest

### Operating System

windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2021-11-17 18:41
Duplicate of #62

**Comment by bombitmanbomb** [comment] 2021-11-18 16:22
Duplicate of #62

**Closed by bombitmanbomb** 2021-11-18 16:22 UTC
Labels: bug, duplicate
