### ISSUE TITLE
[Bug]: Game doesn't start

### ISSUE THREAD

**Issue by dMalox** [Turing-Complete-Game/Suggestions-and-Issues#473] opened 2022-06-16 13:33 UTC
### What happened?

I had the game open and clicked on a previously done level in the "memory" section. With the click the game shut down. I started it again multiple times and the same thing happened every time. Then, after the 5th try or so the game didn't start at all. You can see the window of the game opening, but then closing after 3 seconds or so. Thanks for the help in advance!

### Version

Latest

### Operating System

Windows (10)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-06-16 13:34
Duplicate of #469

**Closed** 2022-07-08 12:19 UTC
Labels: bug, triage
