### ISSUE TITLE
[Bug]: Logic engine page is empty.

### ISSUE THREAD

**Issue by ellamanukyan** [Turing-Complete-Game/Suggestions-and-Issues#353] opened 2022-03-14 09:02 UTC
### What happened?

![photo_2022-03-14_13-00-53](https://user-images.githubusercontent.com/70705614/158138903-b150b4d8-ef27-4ade-834f-b655ff2cfbfd.jpg)

### Version

Latest

### Operating System

windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-03-14 09:21
Create a new schematic via the menu in the top left.

**Comment by ellamanukyan** [comment] 2022-03-14 09:38
> Create a new schematic via the menu in the top left.

thank you, it works

**Comment by MegaIng** [comment] 2022-03-14 12:12
Duplicate of #351

**Closed by MegaIng** 2022-03-14 12:12 UTC
Labels: bug, triage
