### ISSUE TITLE
[Bug]: Signed Less test case outside signed byte range

### ISSUE THREAD

**Issue by Phlosioneer** [Turing-Complete-Game/Suggestions-and-Issues#97] opened 2021-11-22 01:47 UTC
### What happened?

One of the test cases for the Signed Less level is "Is 175 less than -110?"
175 is not representable as a signed byte; maximum positive signed byte is 127. Unsigned 175 would be interpreted as signed -81.
![20211121204629_1](https://user-images.githubusercontent.com/4657718/142789181-c02a9152-d0e7-4c4c-bc75-d557ecb88137.jpg)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2021-11-22 01:48
Half-duplicate of #69

**Comment by Phlosioneer** [comment] 2021-11-22 02:06
Thankfully it's only visual, I was able to fix my bad circuit.

**Comment by Stuffe** [comment] 2021-11-22 13:06
Fixed next patch

**Closed by Stuffe** 2021-11-22 13:06 UTC
Labels: bug, Category: UI, Severity: Low, Category: Levels
