### ISSUE TITLE
[Bug]: Wire path uses 1 length segments when longer than 31

### ISSUE THREAD

**Issue by Pr0metheus42** [Turing-Complete-Game/Suggestions-and-Issues#301] opened 2022-02-10 20:26 UTC
### What happened?

![image](https://user-images.githubusercontent.com/21281226/153490326-ab408944-90b0-45c6-a850-521dd0881fee.png)
In this picture you see a red dot at every point used by the wire path. it is supposed to have segments be as long as possible up to 31 but here it end up using points next to each other the same way the old wires did. 

### Version

Latest

### Operating System

windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment] 2022-02-10 20:27
How are you getting this data?

**Comment by Stuffe** [comment] 2022-02-11 18:48
actually it is not a bug. The game uses full arrays of wire path points for detecting if wire end points overlap other wires or when placing a component etc. It is just compressed when saving

**Comment by Stuffe** [comment] 2022-02-11 18:56
This is fixed in the save_monger script and will be fixed in the next version of the game

**Closed by Stuffe** 2022-02-11 18:56 UTC
Labels: bug, triage
